BUGFIX: cursors.callproc() did not work - used "yield" instead of "raise".
Used to get the error:
  tornado.gen.BadYieldError: yielded unknown object Return...